# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        users:
            entity: { class: UserBundle:User }
    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        areaSegura:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: loginForm
                check_path: loginCheck
                use_referer: false
                success_handler: login_success_handler
            logout:
                path: logout
                target: homepage


    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/editor, roles: [ROLE_EDITOR,ROLE_ADMIN]}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }