# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        user:
            entity: { class: AppBundle:User, property: username }
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        areaSegura:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: loginForm
                check_path: loginCheck
            logout:
                path: logout
                target: homepage

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/editor, roles: [ROLE_EDITOR]}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }