# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  user_login.authentication.handler.login_success_handler.class: UserBundle\Security\Authentication\Handler\LoginSuccessHandler

services:
  login_success_handler:
    class:      %user_login.authentication.handler.login_success_handler.class%
    arguments:  [@router, @security.context]
    tags:
        - { name: 'monolog.logger', channel: 'security' }